//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecordLog
    {
        public int Id { get; set; }
        public int MedicalRecordId { get; set; }
        public string LogType { get; set; }
        public string OldContent { get; set; }
        public string NewContent { get; set; }
        public string AddendumText { get; set; }
        public string Reason { get; set; }
        public int CreatedByUserId { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
        public virtual User User { get; set; }
    }
}
