//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalRecord()
        {
            this.MedicalRecordLogs = new HashSet<MedicalRecordLog>();
        }
    
        public int Id { get; set; }
        public int AppointmentId { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string Prescription { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string BloodPressure { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> LockedAt { get; set; }
        public Nullable<int> LockedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecordLog> MedicalRecordLogs { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
